-include ./objects.mk
-include ./sources.mk
-include ./tc_makefile.mk
include $(CONFIG_PATH)/toolchain.mk

#Tool definitions:
MAKE =$(PLATFORM)/host/bin/make
RM := $(BIN_PATH)/rm -rf

-include ${PROJECT_PATH}/makefile